### ISSUE TITLE
Incompatibility with Twitter API

### ISSUE THREAD

**Issue by jasonkneen** [sdesapio/Classic-ASP-VBScript-OAuth#1]
Hi Scott,

I _think_ a change has happened in the last 24 hours which has broken this code (your demo link no longer works) and it appears to do with XMLHTTP component reading from the twitter API which I think is now returning data in gzip format.

I've done a workaround myself using a proxy page in .NET to re-route the calls and this works.

Jason

**Comment by sdesapio** [comment]
Thanks Jason. Maybe we should incorporate your fix as part of the main Classic ASP OAuth project?

**Comment by jasonkneen** [comment]
No need, Eric nailed it - I've submitted a pull request.
