### ISSUE TITLE
Twitter API now requires connection over SSL

### ISSUE THREAD

**Issue by stupot42** [sdesapio/Classic-ASP-VBScript-OAuth#3]
Could we have an update that allows for the new update that restricts connections to api.twitter.com to TLS/SSL connections only, please.

https://dev.twitter.com/discussions/24239

Currently the script has stopped working for Twitter Oauth requests, including the example on the http://scottdesapio.com/VBScriptOAuth/ website.

I should say, I've updated my instance to use https addresses in the "oauth/_inc/constants_twitter.asp" file and it's working fine, although I don't check the certificate.

**Comment by sdesapio** [comment]
I've updated the endpoints to use SSL and everything appears to be good to go.
